apiVersion: v1
kind: Secret
metadata:
  name: flask-db-secret
type: Opaque
data:
  # Base64 encoded values
  DB_HOST: Zmxhc2tkYi5jeDZtd2V1YXVxLnVzLXdlc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==   # <-- your RDS endpoint
  DB_USER: YWRtaW4=           # 'admin' in base64
  DB_PASSWORD: YWRtaW4xMjM=   # 'admin123' in base64
  DB_NAME: Zmxhc2tkYg==       # 'flaskdb' in base64

