apiVersion: v1
kind: Secret
metadata:
  name: flask-db-secret
type: Opaque
data:
  DB_HOST: Zmxhc2tkYi5jeDZtd2V1YXUxemoudXMtd2VzdC0xLnJkcy5hbWF6b25hd3MuY29t
  DB_NAME: Zmxhc2tkYg==        # your DB name in base64
  DB_USER: YWRtaW4=            # your DB username in base64
  DB_PASSWORD: YWRtaW4xMjM=    # your DB password in base64
